"""Model configuration for the LSTM predictor."""

SEQUENCE_LENGTH = 10
MAX_SEQUENCE_LENGTH = 15
PREDICTION_HORIZON_SECONDS = 120
PREDICTION_STEPS_AHEAD = 24

LSTM_INPUT_SIZE = 1
LSTM_HIDDEN_SIZE = 64
LSTM_NUM_LAYERS = 2
LSTM_DROPOUT = 0.2

TRAINING_EPOCHS = 50
LEARNING_RATE = 0.001
BATCH_SIZE = 32
TRAIN_SPLIT = 0.8
EARLY_STOPPING_PATIENCE = 10

DEFAULT_STUB_PREDICTED_LOAD = 0.5
DEFAULT_STUB_CONFIDENCE = 0.8